name: Build Executables

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:  # Allow manual trigger

# Add permissions for GitHub token
permissions:
  contents: write
  actions: read

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Ensure only PySide6 is available to avoid Qt conflicts
        pip uninstall -y PyQt5 PyQt6 || true
        
    - name: Build executable
      run: |
        python -m PyInstaller ComicsRename.spec
        
    - name: List build output
      run: |
        echo "Build completed. Contents of dist directory:"
        Get-ChildItem -Path dist/ -Force
        echo "All files in dist:"
        Get-ChildItem -Path dist/ -Recurse -File | Select-Object -First 10
        
    - name: Test executable
      run: |
        dist\ComicsRename.exe --version
      continue-on-error: true  # GUI app might not support --version
      
    - name: Get file info
      run: |
        Get-ChildItem -Path dist\ComicsRename.exe -Force
        
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: ComicsRename-Windows
        path: dist/ComicsRename.exe
        if-no-files-found: warn
        
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Ensure only PySide6 is available to avoid Qt conflicts
        pip uninstall -y PyQt5 PyQt6 || true
        
    - name: Build executable
      run: |
        python -m PyInstaller ComicsRename.spec
        
    - name: List build output
      run: |
        echo "Build completed. Contents of dist directory:"
        ls -la dist/
        echo "All files in dist:"
        find dist/ -type f | head -10
        
    - name: Create DMG (optional)
      run: |
        # Create a simple DMG for distribution
        mkdir -p dist/dmg
        cp -r dist/ComicsRename.app dist/dmg/
        # Note: Would need additional setup for signed DMG
        
    - name: Upload macOS executable
      uses: actions/upload-artifact@v4
      with:
        name: ComicsRename-macOS
        path: dist/ComicsRename.app/
        if-no-files-found: warn
        
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxcb-xinerama0 libxcb-cursor0 libxkbcommon-x11-0
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Ensure only PySide6 is available to avoid Qt conflicts
        pip uninstall -y PyQt5 PyQt6 || true
        
    - name: Build executable
      run: |
        python -m PyInstaller ComicsRename.spec
        
    - name: List build output
      run: |
        echo "Build completed. Contents of dist directory:"
        ls -la dist/
        echo "All files in dist:"
        find dist/ -type f | head -10
        
    - name: Upload Linux executable
      uses: actions/upload-artifact@v4
      with:
        name: ComicsRename-Linux
        path: dist/ComicsRename
        if-no-files-found: warn
        
  create-release:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: List downloaded artifacts
      run: |
        echo "Downloaded artifacts:"
        find . -type f -name "*" | head -20
        ls -la
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ComicsRename-Windows/*
          ComicsRename-macOS/*
          ComicsRename-Linux/*
        draft: false
        prerelease: false
        fail_on_unmatched_files: false
        body: |
          ## ComicsRename Release v${{ github.ref_name }}
          
          ### Downloads
          - **Windows**: ComicsRename.exe (standalone executable)
          - **macOS**: ComicsRename.app (application bundle) 
          - **Linux**: ComicsRename (standalone executable)
          
          ### Installation
          1. Download the appropriate file for your platform
          2. Run directly - no installation required!
          
          ### Requirements
          - **Windows**: Windows 10/11 (64-bit)
          - **macOS**: macOS 10.14+ 
          - **Linux**: Modern Linux distribution with X11
          
          All executables are self-contained and include all dependencies.
          
          ### Release Notes
          See the full commit history for detailed changes in this release.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
